import { chromium } from "playwright";
import path from "node:path";
import { fileURLToPath } from "node:url";
const BASE = path.dirname(fileURLToPath(import.meta.url));
const URL_APP = process.env.APP_URL || "https://es-oficial.vercel.app";
const wav = path.join(BASE, "tmp", "mic_voz.wav");
const browser = await chromium.launch({ args: ["--use-fake-ui-for-media-stream","--use-fake-device-for-media-stream",`--use-file-for-fake-audio-capture=${wav}%noloop`] });
const ctx = await browser.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true, permissions:["microphone"] });
const page = await ctx.newPage();
page.on("response", async (r) => { if (r.url().includes("/api/analizar")) console.log("API", r.status(), (await r.text()).slice(0,600)); });
await page.goto(URL_APP, { waitUntil: "networkidle" });
await page.click("text=Grabar");
await page.waitForTimeout(12000);
await page.click("text=Listo");
await page.waitForTimeout(1000);
const tamano = await page.evaluate(() => document.querySelector("audio")?.src?.length ?? 0);
console.log("audio cargado, url len:", tamano);
await page.click("text=Analizar mensaje");
await page.waitForTimeout(90000);
console.log("TEXTO:", (await page.textContent("main")).replace(/\s+/g," ").slice(0,400));
await browser.close();
